baseurl: "/"
title: "GOCON CANADA"
canonifyurls: true
theme: "goconca"
dataDir: "Dat"

GoogleAnalytics: "UA-127047731-1"

params:
  # Conference info
  Name: "GOCON CANADA"
  Description: "Canadian Go Conference"
  Date: "May 31, 2019"
  # Price: "UNKNOWN" # If your event is free, just comment this line
  Venue: "St. James Cathedral Centre"
  Address: "65 Church Street"
  City:  "Toronto"
  State: "Ontario"
  Postcode: "M5C 2E9"
  Images: ["/img/toronto.jpg"]
  GoogleMapsKey: "AIzaSyD75cSNgqEfqbKAq-2aeBJV0gjYBw4Ys88"
  Twitter: goconcanada

  Cfp:
    Title: "Submit your talk proposal now!"
    Url: https://www.papercall.io/goconca

  Organizers:
    - name: Mike Fridman
      homepage: https://mfridman.com
      twitter:
    - name: Zach Goldstein
      homepage: https://zachgoldstein.github.io/
      twitter:
    - name: Lubov Soltan
      homepage: https://lubovsoltan.wixsite.com/lubovsoltan
      twitter:
    - name: Max Gonzih
      homepage: https://gonzih.me/
      twitter:
    - name: Dylan Arbour
      homepage: https://dylanarbour.com/
      twitter:

  Nav:
    - Url: "/#about"
      Title: "About"
    # - Url: "/#schedule"
    #   Title: "Schedule"
    - Url: "/#sponsors"
      Title: "Sponsors"
    # - Url: "/#tickets"
    #   Title: "Tickets"
    - Url: "/blog/"
      Title: "Blog"
    # - Url: "https://www.papercall.io/goconca"
    #   Title: "Call for Papers "
    #   Icon: "fa-scroll"
    #   Target: "_blank"
    - Url: "/speakers/"
      Title: "Speakers"
    # - Url: "/partners/"
    #   Title: "Partners"
    # - Url: "/#diversity-scholarship"
    # Title: "Diversity Scholarship"
    #   Title: "Diversity Scholarship"
    - Url: "/contact/"
      Title: "Contact"
    - Url: "/#mailinglist"
      Title: "Subscribe"
    - Url: "/location/"
      Title: "Location"
    - Url: "/code-of-conduct/"
      Title: "Code of Conduct"
    - Url: "/swag/"
      Title: "Swag"
